
import os
import json
from pathlib import Path
from typing import List, Optional

import anthropic
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")

RUBRIC_MODEL = "claude-sonnet-4-6"

RUBRIC_FRAMEWORK_NOTE = (
    "The rubric domains are prototype formative domains derived from established "
    "clinical communication frameworks, including the Kalamazoo Consensus Statement, "
    "the Calgary-Cambridge Guide, and the SEGUE Framework. "
    "Derivation from established frameworks does not constitute validation. "
    "The rubric has not undergone psychometric validation, inter-rater reliability "
    "testing, or faculty calibration. It should not be used for formal assessment."
)

RUBRIC_VALIDITY_CAUTION = (
    "Rubric scores are generated by a large language model and represent "
    "formative feedback, not validated assessment. They may be incomplete, "
    "inconsistent, or inaccurate. All rubric feedback should be reviewed "
    "by a faculty member before use in formal teaching or research contexts."
)

RUBRIC_CLINICAL_FRAMING = (
    "This prototype does not assess diagnostic accuracy. It provides formative "
    "feedback on how learners communicate while gathering clinically relevant "
    "information and explaining safe next steps in fictional cases."
)

RUBRIC_DOMAINS = [
    {
        "id": "opening_agenda_setting",
        "name": "Opening, Orientation, and Agenda-Setting",
        "framework": "Calgary-Cambridge: Initiating the Session; Kalamazoo: Opening the Discussion",
        "description": (
            "Did the student introduce themselves, establish their role, invite the patient's "
            "full agenda, and — where appropriate — address confidentiality?"
        ),
    },
    {
        "id": "patient_centered_inquiry",
        "name": "Patient-Centered Information Gathering",
        "framework": "Calgary-Cambridge: Gathering Information; SEGUE: Eliciting Information",
        "description": (
            "Did the student use open-ended questions and allow the patient to narrate? "
            "Predominantly closed or interrogatory questioning scores low."
        ),
    },
    {
        "id": "recognition_of_emotion",
        "name": "Recognition of and Response to Emotional Cues",
        "framework": "Kalamazoo: Understanding the Patient's Perspective; Calgary-Cambridge: Building the Relationship",
        "description": (
            "Did the student notice emotional cues and respond to them before continuing "
            "with clinical content?"
        ),
    },
    {
        "id": "empathy_validation",
        "name": "Empathy and Emotional Validation",
        "framework": "Kalamazoo: Building the Relationship; SEGUE: Understanding Patient Perspective",
        "description": (
            "Did the student specifically acknowledge and explore the patient's emotional experience? "
            "Generic phrases without follow-up score 2 at most."
        ),
    },
    {
        "id": "patient_perspective",
        "name": "Eliciting the Patient's Perspective",
        "framework": "Kalamazoo: Understanding the Patient's Perspective; Calgary-Cambridge: ICE",
        "description": (
            "Did the student explore the patient's ideas, specific concerns, and expectations?"
        ),
    },
    {
        "id": "clinical_information_gathering",
        "name": "Clinical Information-Gathering and Safety-Oriented Reasoning",
        "framework": "Calgary-Cambridge: Gathering Information; Kalamazoo: Opening / Information; SEGUE: Eliciting Information",
        "description": (
            "Did the student ask relevant history questions, avoid premature closure, "
            "recognize or follow up on red flags, communicate uncertainty appropriately, "
            "explain possible causes or next steps in plain language, and propose safe next steps? "
            "NOTE: This domain does not assess diagnostic accuracy — it assesses whether "
            "the student communicated effectively WHILE gathering information."
        ),
    },
    {
        "id": "clarity_plain_language",
        "name": "Clarity and Plain-Language Communication",
        "framework": "Calgary-Cambridge: Shared Understanding; SEGUE: Giving Information",
        "description": (
            "Did the student avoid jargon and communicate at the patient's health literacy level? "
            "Did the student check patient understanding?"
        ),
    },
    {
        "id": "shared_decision_making",
        "name": "Shared Decision-Making and Collaborative Planning",
        "framework": "Kalamazoo: Reaching Agreement; Calgary-Cambridge: Planning",
        "description": (
            "Did the student involve the patient in decisions about their care?"
        ),
    },
    {
        "id": "safety_professionalism",
        "name": "Safety, Professionalism, and Encounter Closure",
        "framework": "OSCE professionalism criteria; Calgary-Cambridge: Closing the Session",
        "description": (
            "Did the student avoid unsafe clinical claims, recognize safety concerns, "
            "maintain professional tone, and close the encounter appropriately?"
        ),
    },
    {
        "id": "cue_recognition",
        "name": "Recognition and Response to Nonverbal and Emotional Cues",
        "framework": "Calgary-Cambridge: Building the Relationship — Nonverbal Behavior; Kalamazoo: Understanding the Patient's Perspective",
        "description": (
            "Did the student adapt their communication in response to the patient's visible "
            "emotional state and behavioral cues?"
        ),
    },
]

SCORING_ANCHORS = """
SCORING ANCHORS (apply these strictly — do not inflate scores):

1 = Absent, harmful, dismissive, unsafe, or severely inappropriate
2 = Weak or mostly generic; below minimum professional expectation
3 = Adequate but incomplete, inconsistent, or applied only partially
4 = Strong and patient-centered; above average professional communication
5 = Excellent: specific, responsive, well-timed, contextually appropriate, sustained

MANDATORY CALIBRATION RULES — these override general impressions:
- "I understand" or "I hear you" without follow-up: MAXIMUM 2 for Empathy / Recognition of Emotion.
- Fewer than two open-ended questions: MAXIMUM 2 on Patient-Centered Inquiry.
- Routine use of unexplained medical jargon: MAXIMUM 3 on Clarity.
- Proceeding past a visible emotional cue without acknowledgment: MAXIMUM 2 for Cue Recognition.
- "I'm sure it's nothing" before clinical assessment: Safety flag AND score penalty.
- One-way explanation without eliciting patient preferences: MAXIMUM 2 for Shared Decision-Making.
- Short transcript (fewer than 3 substantive exchanges): Score cautiously; absence of bad behavior
  does not equal good behavior.
- Reassurance before gathering any clinical history: score of 1 on Clinical Information-Gathering.
- Empathy without any clinical questions by turn 3: score of 1-2 on Clinical Information-Gathering.
- Jumping to a diagnosis or specific explanation before adequate history: premature closure penalty
  on Clinical Information-Gathering regardless of whether the diagnosis was correct.
- Explaining reasoning and next steps in plain language while gathering history: scores 4-5 on
  Clinical Information-Gathering.
"""

RUBRIC_PROMPT_TEMPLATE = """
You are an expert clinical communication educator. You are evaluating a medical student's
performance in a simulated patient encounter for FORMATIVE EDUCATIONAL FEEDBACK.
Your evaluation must be honest, specific, and evidence-based. Do not inflate scores.
Do not write "great job" or evaluative praise. Be specific about what was observed.

IMPORTANT FRAMING: This prototype does not assess diagnostic accuracy. Evaluate how the
student communicated while gathering information — not whether they reached the correct diagnosis.

{scoring_anchors}

=== TRANSCRIPT ===
{transcript}

=== PATIENT CONTEXT ===
Patient: {patient_name}, {patient_age} years old
Setting: {setting}
Presenting concern: {chief_concern}
Trust barrier for this case: {trust_barrier}
Patient health literacy level: {health_literacy}

=== KEY CLINICAL QUESTIONS FOR THIS CASE ===
(These are the history questions that are clinically important in this specific case.)
{key_clinical_questions}

=== RED FLAGS TO RECOGNIZE IN THIS CASE ===
{red_flags}

=== AUTOMATED BEHAVIOR TAGS DETECTED ===
(Detected by a separate tagging system. Supporting evidence only — does not replace your judgment.)
{tag_summary}

=== NONVERBAL CUE SUMMARY ===
(Patient visual states observed during the encounter, by turn.)
{cue_summary}

=== SCORING TASK ===
Score the student across all 10 domains. For each domain provide:
  - score (integer 1-5)
  - score_explanation (one sentence based on specific transcript evidence)
  - evidence (a direct quote from a student message, or "Not observed in transcript")
  - improvement (specific, actionable suggestion)
  - stronger_alternative (an example of a better student response for the key moment)

DOMAINS:

1. opening_agenda_setting — Opening, Orientation, and Agenda-Setting
   Did the student introduce themselves, establish their role, invite the agenda, and address confidentiality?
   1: No introduction or role; encounter starts without orientation
   3: Brief introduction; agenda partially established
   5: Clear introduction; patient invited to share full agenda; confidentiality addressed where relevant

2. patient_centered_inquiry — Patient-Centered Information Gathering
   Did the student use open questions and give the patient space to narrate?
   1: Only closed questions; patient given no space
   3: Mix of open and closed; open questions inconsistently applied
   5: Consistently open inquiry; patient invited to describe freely

3. recognition_of_emotion — Recognition of and Response to Emotional Cues
   Did the student notice and respond to visible emotional cues before continuing clinically?
   1: Ignores cues; moves to clinical questions despite visible distress
   3: Notices emotion but responds generically without follow-through
   5: Names the specific emotion; validates it; creates space before continuing

4. empathy_validation — Empathy and Emotional Validation
   Did the student specifically acknowledge and explore the patient's emotional experience?
   1: No acknowledgment; dismissive or tone-inappropriate
   3: Generic empathy without exploration or follow-up
   5: Names specific emotion, validates, creates space, follows through consistently

5. patient_perspective — Eliciting the Patient's Perspective
   Did the student explore the patient's ideas, specific concerns, and expectations?
   1: No exploration of patient perspective beyond surface complaint
   3: Acknowledges concerns but does not explore underlying ideas or expectations
   5: Explores ideas (what the patient thinks), concerns (fears), and expectations (what they hoped for)

6. clinical_information_gathering — Clinical Information-Gathering and Safety-Oriented Reasoning
   NOTE: Do NOT assess diagnostic accuracy. Assess how the student communicated while gathering information.
   Did the student: ask relevant history questions, avoid premature closure, recognize/respond
   to red flags, communicate uncertainty appropriately, explain reasoning in plain language,
   propose safe next steps?

   The key clinical questions for this specific case are listed above — use these to evaluate
   whether the student gathered the information that matters.

   1: Fails to ask relevant clinical history questions; offers reassurance or diagnosis before
      adequate history; ignores red flags; gives unsafe or premature advice
   2: Asks a few history questions but misses most of what matters; no red flag awareness;
      or empathy without clinical progress across the encounter
   3: Gathers some relevant information but misses important areas; clinical reasoning
      communicated unclearly or incompletely
   4: Gathers most key history areas; identifies at least one red flag; explains next steps
      in plain language; avoids premature closure
   5: Gathers focused relevant history covering most key areas; recognizes safety issues;
      explains uncertainty honestly; proposes specific, safe next steps collaboratively

7. clarity_plain_language — Clarity and Plain-Language Communication
   Was language clear and appropriate to the patient's health literacy level?
   1: Heavy unexplained jargon; patient likely confused
   3: Generally clear with occasional unexplained terms; no comprehension check
   5: Consistently plain; tailored to patient; comprehension checked

8. shared_decision_making — Shared Decision-Making and Collaborative Planning
   Did the student involve the patient in care decisions?
   1: Purely directive; patient has no input
   3: Mentions options but does not elicit preference or address barriers
   5: Presents options; elicits values and barriers; confirms patient's decision

9. safety_professionalism — Safety, Professionalism, and Encounter Closure
   Did the student maintain safety, professionalism, and appropriate closure?
   1: Unsafe claim, missed red flag, false reassurance, or professionalism failure
   3: Generally safe; minor gaps in safety or closure
   5: Proactively safe; professional throughout; encounter closed with clear plan

10. cue_recognition — Recognition and Response to Nonverbal/Emotional Cues
    Did the student adapt their communication when the patient's state changed?
    1: Student behavior appears unresponsive to patient state changes throughout
    3: Some adaptation observed, but inconsistent or delayed
    5: Student consistently adapts approach to visible state changes

=== OUTPUT FORMAT ===
Return ONLY the following JSON. No markdown code blocks. No text before or after.
All values must be plain strings (no markdown inside string values).

{{
  "domains": [
    {{
      "id": "opening_agenda_setting",
      "name": "Opening, Orientation, and Agenda-Setting",
      "score": <integer 1-5>,
      "score_explanation": "<one sentence based on transcript evidence>",
      "evidence": "<direct quote from student, or 'Not observed in transcript'>",
      "improvement": "<specific, actionable suggestion>",
      "stronger_alternative": "<example of a better student response>"
    }},
    {{
      "id": "patient_centered_inquiry",
      "name": "Patient-Centered Information Gathering",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }},
    {{
      "id": "recognition_of_emotion",
      "name": "Recognition of and Response to Emotional Cues",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }},
    {{
      "id": "empathy_validation",
      "name": "Empathy and Emotional Validation",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }},
    {{
      "id": "patient_perspective",
      "name": "Eliciting the Patient's Perspective",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }},
    {{
      "id": "clinical_information_gathering",
      "name": "Clinical Information-Gathering and Safety-Oriented Reasoning",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }},
    {{
      "id": "clarity_plain_language",
      "name": "Clarity and Plain-Language Communication",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }},
    {{
      "id": "shared_decision_making",
      "name": "Shared Decision-Making and Collaborative Planning",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }},
    {{
      "id": "safety_professionalism",
      "name": "Safety, Professionalism, and Encounter Closure",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }},
    {{
      "id": "cue_recognition",
      "name": "Recognition and Response to Nonverbal/Emotional Cues",
      "score": <integer 1-5>,
      "score_explanation": "...", "evidence": "...", "improvement": "...", "stronger_alternative": "..."
    }}
  ],
  "overall_profile": "<2-3 honest sentences describing the student's communication profile — no praise, specific and direct>",
  "communication_warmth_summary": "<1-2 sentences on how well the student managed the emotional/relational dimension>",
  "clinical_focus_summary": "<1-2 sentences on how well the student gathered clinically relevant information>",
  "integration_summary": "<1-2 sentences on whether the student balanced warmth and clinical focus — or was strong in one but weak in the other>",
  "missed_clinical_info": [
    "<specific clinical question that was not asked but should have been, based on the key clinical questions for this case>",
    "<another missed clinical area if present>"
  ],
  "missed_emotional_concerns": [
    "<specific emotional cue or patient concern that was not acknowledged>",
    "<another if present>"
  ],
  "integrated_improvement_example": "<A single example of a student response that integrates both emotional acknowledgment AND a relevant clinical question. Show how they can be combined in one turn.>",
  "missed_opportunities": [
    "<specific missed moment: describe the patient cue and what the student could have done>",
    "<another if present>"
  ],
  "safety_flags": [
    "<specific safety or professionalism concern, or 'No major safety concerns identified'>"
  ],
  "reflection_prompts": [
    "<first reflection question, specific to this transcript>",
    "<second: ask about a moment where clinical and emotional demands were in tension>",
    "<third: ask what visual or emotional cue the student noticed and how it changed their next response>"
  ]
}}
"""

def _format_transcript(conversation_history: List[dict], patient_name: str) -> str:
    """Format conversation history into a readable transcript for the rubric prompt."""
    lines = []
    turn = 1
    for msg in conversation_history:
        role    = msg.get("role", "")
        content = msg.get("content", "").strip()
        if content.startswith("(The consultation begins"):
            continue
        if role == "user":
            lines.append(f"[STUDENT — Turn {turn}]: {content}")
        elif role == "assistant":
            lines.append(f"[{patient_name.upper()} (Simulated Patient)]: {content}")
            turn += 1
    return "\n\n".join(lines) if lines else "No conversation turns recorded."

def _format_tag_summary(tag_counts: dict) -> str:
    """Format accumulated tag counts into a readable summary."""
    if not tag_counts:
        return "No behavioral tags were recorded for this session."

    positive = {
        "empathy", "confidentiality_explanation", "open_question",
        "gives_patient_control", "explains_question_purpose", "asks_permission",
        "respectful_sensitive_question", "communication_repair",
        "relevant_clinical_question", "red_flag_acknowledged",
        "appropriate_uncertainty", "plain_explanation", "safe_next_step", "clear_closure",
    }
    negative = {
        "judgmental_tone", "rushed_sensitive_question", "ignored_emotion",
        "medical_jargon", "unprofessional_language", "dismissive_reassurance",
        "failed_role_establishment", "false_reassurance", "coercive_pressure",
        "accusatory_question", "overpromised_confidentiality",
        "repeated_pressure", "critical_boundary_violation",
        "premature_closure", "reassurance_without_basis", "clinical_drift",
    }

    pos_lines, neg_lines, other_lines = [], [], []
    for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1]):
        entry = f"  {tag}: {count} time(s)"
        if tag in positive:
            pos_lines.append(entry)
        elif tag in negative:
            neg_lines.append(entry)
        else:
            other_lines.append(entry)

    parts = []
    if pos_lines:
        parts.append("Positive behaviors detected:\n" + "\n".join(pos_lines))
    if neg_lines:
        parts.append("Concerning behaviors detected:\n" + "\n".join(neg_lines))
    if other_lines:
        parts.append("Other behaviors:\n" + "\n".join(other_lines))
    return "\n\n".join(parts) if parts else "No tags recorded."

def _format_cue_summary(nonverbal_timeline: List[dict]) -> str:
    """Format the nonverbal cue timeline for inclusion in the rubric prompt."""
    if not nonverbal_timeline:
        return "No nonverbal cue data recorded for this session."

    lines = []
    for entry in nonverbal_timeline:
        turn     = entry.get("turn", "?")
        label    = entry.get("cue_label", entry.get("visual_state", "unknown"))
        behavior = entry.get("student_behavior", "Not recorded")
        lines.append(f"  Turn {turn}: Patient visual state — {label}. {behavior}.")
    return "\n".join(lines)

def _format_clinical_questions(key_clinical_questions: List[str]) -> str:
    if not key_clinical_questions:
        return "No case-specific clinical questions provided."
    return "\n".join(f"  - {q}" for q in key_clinical_questions)

def _format_red_flags(red_flags: List[str]) -> str:
    if not red_flags:
        return "No case-specific red flags provided."
    return "\n".join(f"  - {r}" for r in red_flags)

def score_session(
    conversation_history: List[dict],
    patient_name: str,
    patient_age: int,
    setting: str,
    chief_concern: str,
    trust_barrier: str,
    health_literacy: str,
    tag_counts: dict,
    nonverbal_timeline: List[dict] = None,
    key_clinical_questions: List[str] = None,
    red_flags: List[str] = None,
) -> Optional[dict]:
    """
    Score a completed simulation session using a 10-domain formative rubric.

    Calls Claude Sonnet with the full transcript, case context, and clinical
    task data. Returns a structured dict of rubric scores, or None on failure.

    NOTE: This does not assess diagnostic accuracy — it assesses clinical
    communication quality while gathering information.

    Args:
        conversation_history:   Full conversation history.
        patient_name:           Patient's first name.
        patient_age:            Patient's age.
        setting:                Clinical setting string.
        chief_concern:          Patient's presenting complaint.
        trust_barrier:          Case-specific trust barrier.
        health_literacy:        "Low" | "Moderate" | "High"
        tag_counts:             Accumulated behavioral tag counts.
        nonverbal_timeline:     Nonverbal cue dicts per turn (optional).
        key_clinical_questions: Case-specific key history questions.
        red_flags:              Case-specific red flags to recognize.

    Returns:
        Dict with rubric data, or None if scoring fails.
    """
    api_key = os.getenv("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        return None

    transcript   = _format_transcript(conversation_history, patient_name)
    tag_summary  = _format_tag_summary(tag_counts)
    cue_summary  = _format_cue_summary(nonverbal_timeline or [])
    kq_text      = _format_clinical_questions(key_clinical_questions or [])
    rf_text      = _format_red_flags(red_flags or [])

    prompt = RUBRIC_PROMPT_TEMPLATE.format(
        scoring_anchors=SCORING_ANCHORS,
        transcript=transcript,
        patient_name=patient_name,
        patient_age=patient_age,
        setting=setting,
        chief_concern=chief_concern,
        trust_barrier=trust_barrier,
        health_literacy=health_literacy,
        key_clinical_questions=kq_text,
        red_flags=rf_text,
        tag_summary=tag_summary,
        cue_summary=cue_summary,
    )

    client = anthropic.Anthropic(api_key=api_key)

    try:
        response = client.messages.create(
            model=RUBRIC_MODEL,
            max_tokens=4000,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = response.content[0].text.strip()

        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        raw = raw.strip()

        result = json.loads(raw)

        if "domains" not in result or len(result["domains"]) != 10:
            return None

        for domain in result["domains"]:
            score = domain.get("score")
            if not isinstance(score, int) or score < 1 or score > 5:
                domain["score"] = max(1, min(5, int(score) if score else 1))

        return result

    except (json.JSONDecodeError, IndexError, KeyError, anthropic.APIError, ValueError):
        return None

def get_score_label(score: int) -> str:
    """Return a text label for a 1-5 score."""
    return {
        1: "Absent / Harmful",
        2: "Weak / Generic",
        3: "Adequate",
        4: "Strong",
        5: "Excellent",
    }.get(score, "Unknown")

def get_overall_score(rubric_result: dict) -> float:
    """Calculate the mean score across all domains. Returns 0.0 on failure."""
    if not rubric_result or "domains" not in rubric_result:
        return 0.0
    scores = [d.get("score", 0) for d in rubric_result["domains"] if isinstance(d.get("score"), int)]
    return round(sum(scores) / len(scores), 1) if scores else 0.0
